// frontend/src/components/SidePanel.vue
<template>
  <div class="side-panel">
    <el-tabs v-model="activeTab" class="side-tabs">
      <el-tab-pane label="🌐 翻译" name="translate">
        <div class="panel-body">
          <div style="display:flex;gap:6px;margin-bottom:8px">
            <el-select v-model="sourceLang" size="small" style="width:75px">
              <el-option label="自动" value="auto" />
              <el-option label="中文" value="zh" />
              <el-option label="English" value="en" />
            </el-select>
            <el-button size="small" @click="swapLangs">⇄</el-button>
            <el-select v-model="targetLang" size="small" style="width:75px">
              <el-option label="中文" value="zh" />
              <el-option label="English" value="en" />
            </el-select>
            <el-button type="primary" size="small" @click="translateText">翻译</el-button>
            <el-button size="small" @click="fillPageText">📄 当前页</el-button>
          </div>
          <el-input v-model="sourceText" :rows="3" type="textarea" placeholder="在 PDF 中选中文字后点翻译，或点「当前页」" />
          <el-input v-model="resultText" :rows="4" type="textarea" readonly placeholder="翻译结果" style="margin-top:6px" />
          <el-button size="small" style="margin-top:6px;width:100%" @click="fullTranslate">全文翻译</el-button>
        </div>
      </el-tab-pane>
      <el-tab-pane label="📝 笔记" name="notes">
        <div class="panel-body">
          <div style="display:flex;gap:6px;margin-bottom:8px">
            <el-color-picker v-model="noteColor" :predefine="['#FFD700','#FF6B6B','#51CF66','#339AF0','#CC66FF']" size="small" />
            <el-button type="primary" size="small" @click="addNote">添加笔记</el-button>
          </div>
          <el-input v-model="noteContent" :rows="2" type="textarea" placeholder="输入笔记内容..." />
          <div class="note-list">
            <div v-for="n in notes" :key="n.id" class="note-item" :style="{ borderLeftColor: n.color || '#FFD700' }">
              <div class="note-text">{{ n.content }}</div>
              <div style="font-size:11px;color:#909399">第{{ n.page_num }}页</div>
              <el-button text size="small" @click="deleteNote(n.id)" style="margin-top:4px">🗑️</el-button>
            </div>
            <el-empty v-if="!notes.length" description="暂无笔记" :image-size="40" />
          </div>
        </div>
      </el-tab-pane>
      <el-tab-pane label="🔖 书签" name="bookmarks">
        <div class="panel-body">
          <div v-for="b in bookmarks" :key="b.id" class="bm-item" @click="goToPage(b.page_num)">
            🔖 第{{ b.page_num }}页
          </div>
          <el-empty v-if="!bookmarks.length" description="暂无书签" :image-size="40" />
        </div>
      </el-tab-pane>
      <el-tab-pane label="🧠 图谱" name="knowledge">
        <div class="panel-body">
          <div ref="graphRef" style="width:100%;height:280px"></div>
          <div v-if="graphNodeDetail" style="font-size:12px;padding:8px;background:#f5f7fa;border-radius:4px;margin-top:8px">
            <strong>{{ graphNodeDetail.name }}</strong><br><span style="color:#909399">{{ graphNodeDetail.desc }}</span>
          </div>
          <div style="display:flex;gap:6px;margin-top:8px">
            <el-button size="small" type="primary" @click="extractGraph">🔄 生成图谱</el-button>
            <el-button size="small" @click="exportGraph">📤 导出</el-button>
          </div>
        </div>
      </el-tab-pane>
    </el-tabs>
  </div>
</template>

<script setup>
import { ref, watch, onMounted, nextTick } from 'vue'
import { api } from '../api.js'
import { ElMessage } from 'element-plus'

const props = defineProps({ book: Object, page: Number, activeTab: String })
const emit = defineEmits(['goToPage'])

const activeTab = ref('translate')
const sourceLang = ref('auto')
const targetLang = ref('zh')
const sourceText = ref('')
const resultText = ref('')
const noteContent = ref('')
const noteColor = ref('#FFD700')
const notes = ref([])
const bookmarks = ref([])
const graphRef = ref(null)
let graphChart = null
const graphNodeDetail = ref(null)

watch(() => props.activeTab, (v) => { activeTab.value = v }, { immediate: true })
watch(() => props.book, (b) => { if (b) { loadNotes(b.id); loadBookmarks(b.id); loadGraph(b.id) } }, { immediate: true })

// PDF 选中文本自动填充
onMounted(() => {
  window.addEventListener('pdf-selection', (e) => {
    if (e.detail && activeTab.value === 'translate') sourceText.value = e.detail.slice(0, 3000)
  })
})

function swapLangs() {
  const s = sourceLang.value; const t = targetLang.value
  if (s !== 'auto') { sourceLang.value = t; targetLang.value = s }
  const st = sourceText.value; const tt = resultText.value
  if (st || tt) { sourceText.value = tt; resultText.value = st }
}

async function translateText() {
  let text = sourceText.value.trim()
  if (!text) { ElMessage.info('请先输入文本'); return }
  resultText.value = '⏳ 翻译中（模型推理较慢，请稍候）...'
  try {
    const r = await api.translate({ text, source_lang: sourceLang.value, target_lang: targetLang.value })
    resultText.value = r.translated_text || '翻译失败'
  } catch { resultText.value = '⏱️ 翻译超时或失败' }
}

async function fillPageText() {
  if (!props.book) { ElMessage.info('请先打开一本书'); return }
  try {
    const r = await api.getPageContent(props.book.id, props.page)
    if (r.content) { sourceText.value = r.content.slice(0, 3000) }
    else { ElMessage.info('当前页无文本') }
  } catch { ElMessage.info('获取文本失败') }
}

async function fullTranslate() {
  if (!props.book) { ElMessage.warning('请先打开一本书'); return }
  try {
    await api.translateFull({ book_id: props.book.id, target_lang: targetLang.value })
    ElMessage.success('全文翻译任务已启动')
  } catch { ElMessage.error('启动失败') }
}

async function loadNotes(bid) { try { const r = await api.getNotes(bid); notes.value = r.notes || [] } catch {} }
async function loadBookmarks(bid) { try { const r = await api.getBookmarks(bid); bookmarks.value = r.bookmarks || [] } catch {} }
async function addNote() {
  if (!props.book) return
  if (!noteContent.value.trim()) { ElMessage.warning('请输入笔记内容'); return }
  await api.addNote(props.book.id, { page_num: props.page, content: noteContent.value, color: noteColor.value })
  ElMessage.success('笔记已添加'); noteContent.value = ''; loadNotes(props.book.id)
}
async function deleteNote(nid) { await api.deleteNote(nid); loadNotes(props.book.id) }
function goToPage(pn) { emit('goToPage', pn) }

async function loadGraph(bid) {
  try {
    const data = await api.getKnowledgeGraph(bid)
    if (!data.nodes || !data.nodes.length) return
    await nextTick()
    if (!graphRef.value) return
    if (!graphChart) {
      const echarts = (await import('echarts')).default
      graphChart = echarts.init(graphRef.value)
    }
    graphChart.setOption({
      tooltip: { formatter: p => p.dataType === 'node' ? `<strong>${p.name}</strong><br/>${p.data._desc||''}` : '' },
      series: [{
        type: 'graph', layout: 'force',
        data: data.nodes.map(n => ({id:n.id,name:n.label,symbolSize:Math.max(8,20-n.level*3),category:n.level,itemStyle:{color:['#4263eb','#51cf66','#ffd43b','#ff6b6b'][n.level]||'#748ffc'},_desc:n.description})),
        edges: data.edges.map(e => ({source:e.source,target:e.target,label:{show:true,formatter:e.label||'',fontSize:9},lineStyle:{color:'#adb5bd',width:1,curveness:0.2,opacity:0.5}})),
        roam: true, draggable: true, force: { repulsion: 300, edgeLength: [60,150], gravity: 0.1 },
        label: { show: true, position: 'right', fontSize: 10 },
      }]
    })
    graphChart.on('click', p => { if (p.dataType === 'node') graphNodeDetail.value = { name: p.name, desc: p.data._desc||'暂无描述' } })
  } catch {}
}
function extractGraph() {
  if (!props.book) return
  api.extractKnowledge(props.book.id); ElMessage.success('知识抽取已启动')
  setTimeout(() => loadGraph(props.book.id), 3000)
}
function exportGraph() {
  if (graphChart) {
    const url = graphChart.getDataURL({ type: 'png', pixelRatio: 2, backgroundColor: '#fff' })
    const a = document.createElement('a'); a.href = url; a.download = `knowledge_${props.book?.id||0}.png`; a.click()
  }
}
</script>

<style scoped>
.side-panel { display:flex;flex-direction:column;height:100%;overflow:hidden }
.side-tabs { flex:1;display:flex;flex-direction:column }
.side-tabs :deep(.el-tabs__header) { margin:0;background:#f5f7fa;border-bottom:1px solid var(--el-border-color-light) }
.side-tabs :deep(.el-tabs__nav-wrap) { padding:0 4px }
.side-tabs :deep(.el-tabs__item) { height:32px;line-height:32px;padding:0 10px;font-size:12px;border:1px solid transparent;border-bottom:none;border-radius:4px 4px 0 0;margin:0 1px }
.side-tabs :deep(.el-tabs__item.is-active) { background:#fff;border-color:var(--el-border-color-light);border-bottom-color:#fff }
.side-tabs :deep(.el-tabs__active-bar) { display:none }
.side-tabs :deep(.el-tabs__content) { flex:1;overflow:hidden;background:#fff }
.side-tabs :deep(.el-tab-pane) { height:100%;overflow-y:auto }
.panel-body { padding:12px;display:flex;flex-direction:column;gap:4px }
.note-list { flex:1;overflow-y:auto;margin-top:8px }
.note-item { padding:8px;margin-bottom:6px;border-radius:4px;border-left:3px solid #ffd43b;background:#f5f7fa;font-size:12px }
.note-text { margin-bottom:2px }
.bm-item { padding:6px 8px;margin-bottom:2px;border-radius:4px;cursor:pointer;font-size:12px }
.bm-item:hover { background:#f5f7fa }
</style>

// frontend/src/components/SidePanel.jsx
import React, { useState, useEffect, useRef } from 'react'
import { api } from '../api'
import { Select, Button, Input, message, notification } from 'antd'
import { DeleteOutlined, ApartmentOutlined } from '@ant-design/icons'

function cleanText(text) {
  if (!text) return ''
  let t = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n')
  t = t.replace(/\n{3,}/g, '\n\n')
  t = t.replace(/([^\n])\n(?=[^\n])/g, '$1 ')
  t = t.replace(/[ \t]+/g, ' ')
  t = t.replace(/[-￰-￿​-‍﻿◀▶▲▼←→↑↓↔↕♦♥♣♠•●○◆◇■□▬▲△▼▽◆◇○◎●◐◑★☆☛☚✔✗✘‰‼‽‽]/g, '')
  // 去掉页眉页脚：页码、页数等信息
  t = t.replace(/第\s*\d+\s*\/\s*\d+\s*页.*?(?:\n|$)/g, '\n')
  t = t.replace(/^\s*\d+\s*\n/gm, '')
  t = t.split('\n').map(l => l.trim()).join('\n').trim()
  return t
}

const TABS = [
  { key: 'translate', label: '翻译', icon: '🌐' },
  { key: 'notes', label: '笔记', icon: '📝' },
  { key: 'bookmarks', label: '书签', icon: '🔖' },
  { key: 'knowledge', label: '图谱', icon: <ApartmentOutlined /> },
]

export default function SidePanel({ book, page, activeTab, onTabChange }) {
  const [sourceText, setSourceText] = useState('')
  const [resultText, setResultText] = useState('')
  const [translating, setTranslating] = useState(false)
  const [sourceLang, setSourceLang] = useState('auto')
  const [targetLang, setTargetLang] = useState('zh')
  const [notes, setNotes] = useState([])
  const [noteText, setNoteText] = useState('')
  const [noteColor, setNoteColor] = useState('#FFD700')
  const [bookmarks, setBookmarks] = useState([])
  const [editingBmId, setEditingBmId] = useState(null)
  const [editingBmTitle, setEditingBmTitle] = useState('')
  const [graphExists, setGraphExists] = useState(false)
  const graphRef = useRef(null)
  const pollRef = useRef(null)

  useEffect(() => {
    const h = (e) => { if (e.detail) setSourceText(cleanText(e.detail.slice(0, 5000))) }
    window.addEventListener('pdf-selection', h)
    return () => window.removeEventListener('pdf-selection', h)
  }, [])

  useEffect(() => {
    if (!book) return
    api.getNotes(book.id).then(r => setNotes(r.notes || [])).catch(() => {})
    api.getBookmarks(book.id).then(r => setBookmarks(r.bookmarks || [])).catch(() => {})
    loadGraph(book.id)
  }, [book])

  useEffect(() => {
    const h = () => { if (book) api.getBookmarks(book.id).then(r => setBookmarks(r.bookmarks || [])).catch(() => {}) }
    window.addEventListener('refresh-bookmarks', h)
    return () => window.removeEventListener('refresh-bookmarks', h)
  }, [book])

  // 切到图谱标签时自动加载（数据可能已在后台生成完毕）
  useEffect(() => {
    if (activeTab === 'knowledge' && book) loadGraph(book.id)
  }, [activeTab, book])

  // 组件卸载时清理后台轮询
  useEffect(() => {
    return () => { if (pollRef.current && typeof pollRef.current === 'number') clearInterval(pollRef.current); pollRef.current = null }
  }, [])

  const translate = async () => {
    const t = sourceText.trim()
    if (!t) { message.info('请输入文本'); return }
    setTranslating(true)
    setResultText('⏳ 翻译中...')
    try {
      const r = await api.translate({ text: t, source_lang: sourceLang, target_lang: targetLang })
      if (r.error) { setResultText('翻译失败: ' + r.error); return }
      setResultText(r.translated_text || '翻译失败')
    } catch (e) { setResultText('翻译失败: ' + (e.message || '')) }
    setTranslating(false)
  }

  const fillPageText = async () => {
    if (!book) return
    try {
      const r = await api.getPageContent(book.id, page)
      if (r.content) setSourceText(cleanText(r.content.slice(0, 3000)))
    } catch {}
  }

  const fullTranslate = async () => {
    if (!book) return
    await api.translateFull({ book_id: book.id, target_lang: targetLang })
    message.success('全文翻译已启动')
  }

  const addNote = async () => {
    if (!book || !noteText.trim()) return
    await api.addNote(book.id, { page_num: page, content: noteText, color: noteColor })
    message.success('笔记已添加')
    setNoteText('')
    const r = await api.getNotes(book.id)
    setNotes(r.notes || [])
  }

  const deleteNote = async (id) => {
    await api.deleteNote(id)
    const r = await api.getNotes(book.id)
    setNotes(r.notes || [])
  }

  const loadGraph = async (bid) => {
    try {
      const data = await api.getKnowledgeGraph(bid)
      if (!data.nodes || !data.nodes.length) {
        setGraphExists(false)
        return
      }
      setGraphExists(true)
      const echarts = (await import('echarts')).default
      // 用 rAF 等 DOM 就绪后再初始化图表
      requestAnimationFrame(() => {
        if (!graphRef.current) return
        const chart = echarts.init(graphRef.current)
        chart.setOption({
          tooltip: { formatter: (p) => p.dataType === 'node' ? p.name : '' },
          series: [{ type: 'graph', layout: 'force', roam: true, draggable: true,
            data: data.nodes.map(n => ({ id: n.id, name: n.label, symbolSize: Math.max(8, 20 - n.level * 3), itemStyle: { color: ['#4263eb', '#51cf66', '#ffd43b', '#ff6b6b'][n.level] || '#748ffc' } })),
            edges: data.edges.map(e => ({ source: e.source, target: e.target, label: { show: true, formatter: e.label || '', fontSize: 9 }, lineStyle: { color: '#adb5bd', width: 1, curveness: 0.2 } })),
            force: { repulsion: 300, edgeLength: [60, 150] }, label: { show: true, position: 'right', fontSize: 10 },
          }]
        })
      })
    } catch (e) { console.error('[图谱] 加载失败:', e) }
  }

  // Language options
  const langOpts = [
    { value: 'auto', label: '自动检测' }, { value: 'zh', label: '中文' }, { value: 'en', label: 'English' },
    { value: 'ja', label: '日本語' }, { value: 'ko', label: '한국어' }, { value: 'fr', label: 'Français' },
    { value: 'de', label: 'Deutsch' }, { value: 'es', label: 'Español' }, { value: 'ru', label: 'Русский' },
  ]

  return (
    <div style={{ display: 'flex', height: '100%', overflow: 'hidden' }}>
      {/* 面板内容（左侧） */}
      <div style={{ flex: 1, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
        {activeTab === 'translate' && (
          <div className="panel-body" style={{ flex: 1 }}>
            <div className="panel-controls">
              <Select value={sourceLang} onChange={setSourceLang} size="small" style={{ width: 100 }} options={langOpts} />
              <Button size="small" onClick={() => { const s = sourceLang; setSourceLang(targetLang); setTargetLang(s) }}>⇄</Button>
              <Select value={targetLang} onChange={setTargetLang} size="small" style={{ width: 100 }} options={langOpts.filter(o => o.value !== 'auto')} />
              <Button type="primary" size="small" onClick={translate} loading={translating}>翻译</Button>
              <Button size="small" onClick={fillPageText}>当前页</Button>
              <Button size="small" onClick={() => { setSourceText(''); setResultText('') }}>清除</Button>
            </div>
            <Input.TextArea className="panel-textarea" value={sourceText} onChange={e => setSourceText(e.target.value)} placeholder="选中文本后自动填充或点当前页" />
            <Input.TextArea className="panel-textarea" value={resultText} readOnly placeholder="翻译结果" />
            <Button size="small" block onClick={fullTranslate}>全文翻译</Button>
          </div>
        )}
        {activeTab === 'notes' && (
          <div className="panel-body" style={{ flex: 1 }}>
            <Input.TextArea value={noteText} onChange={e => setNoteText(e.target.value)} rows={2} placeholder="输入笔记..." />
            <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
              {['#FFD700', '#FF6B6B', '#51CF66', '#339AF0', '#CC66FF'].map(c => (
                <div key={c} onClick={() => setNoteColor(c)} style={{ width: 18, height: 18, borderRadius: '50%', background: c, cursor: 'pointer', border: noteColor === c ? '2px solid #303133' : '2px solid transparent', flexShrink: 0 }} />
              ))}
              <Button type="primary" size="small" onClick={addNote}>添加笔记</Button>
            </div>
            <div className="panel-scroll" style={{ flex: 1, overflowY: 'auto', marginTop: 8 }}>
              {notes.length === 0 ? <div style={{ textAlign: 'center', color: '#c0c4cc', padding: 20 }}>暂无笔记</div> : notes.map(n => (
                <div key={n.id} style={{ padding: 8, marginBottom: 6, borderRadius: 4, borderLeft: '3px solid ' + (n.color || '#ffd43b'), background: '#f5f7fa', fontSize: 12 }}>
                  <div>{n.content}</div>
                  <div style={{ fontSize: 11, color: '#909399' }}>第{n.page_num}页</div>
                  <Button type="text" size="small" danger icon={<DeleteOutlined />} onClick={() => deleteNote(n.id)} />
                </div>
              ))}
            </div>
          </div>
        )}
        {activeTab === 'bookmarks' && (
          <div className="panel-body" style={{ flex: 1 }}>
            <div className="panel-scroll" style={{ flex: 1, overflowY: 'auto' }}>
              {bookmarks.length === 0 ? <div style={{ textAlign: 'center', color: '#c0c4cc', padding: 20 }}>暂无书签</div> : bookmarks.map(b => (
                <div key={b.id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '6px 8px', fontSize: 12, borderBottom: '1px solid #f0f0f0', cursor: 'pointer' }}
                  onClick={() => { if (editingBmId !== b.id) window.dispatchEvent(new CustomEvent('go-to-page', { detail: b.page_num })) }}>
                  <div style={{ flex: 1, minWidth: 0, marginRight: 8 }} onClick={e => e.stopPropagation()}>
                    {editingBmId === b.id ? (
                      <Input size="small" value={editingBmTitle} autoFocus
                        onChange={e => setEditingBmTitle(e.target.value)}
                        onBlur={async () => {
                          if (editingBmTitle.trim()) {
                            await api.updateBookmark(b.id, { title: editingBmTitle.trim() })
                            const r = await api.getBookmarks(book.id)
                            setBookmarks(r.bookmarks || [])
                          }
                          setEditingBmId(null)
                        }}
                        onPressEnter={async () => {
                          if (editingBmTitle.trim()) {
                            await api.updateBookmark(b.id, { title: editingBmTitle.trim() })
                            const r = await api.getBookmarks(book.id)
                            setBookmarks(r.bookmarks || [])
                          }
                          setEditingBmId(null)
                        }}
                      />
                    ) : (
                      <span onClick={() => { setEditingBmId(b.id); setEditingBmTitle(b.title || `第${b.page_num}页`) }} style={{ color: '#303133' }}>{b.title || `第${b.page_num}页`}</span>
                    )}
                  </div>
                  <span style={{ color: '#909399', flexShrink: 0, fontSize: 11, marginRight: 4 }}>第{b.page_num}页</span>
                  <Button type="text" size="small" danger icon={<DeleteOutlined />} onClick={async (e) => { e.stopPropagation(); await api.deleteBookmark(b.id); const r = await api.getBookmarks(book.id); setBookmarks(r.bookmarks || []) }} />
                </div>
              ))}
            </div>
          </div>
        )}
        {activeTab === 'knowledge' && (
          <div className="panel-body" style={{ flex: 1 }}>
            <div ref={graphRef} className="panel-graph" style={{ flex: 1, minHeight: 150 }}>
              {!graphExists && !pollRef.current && (
                <div style={{ textAlign: 'center', color: '#c0c4cc', padding: 40, fontSize: 13 }}>
                  <div style={{ fontSize: 36, marginBottom: 8 }}>🔗</div>
                  暂无图谱数据，点击下方按钮生成
                </div>
              )}
              {pollRef.current && (
                <div style={{ textAlign: 'center', color: '#909399', padding: 40, fontSize: 13 }}>
                  <div style={{ fontSize: 36, marginBottom: 8 }}>⏳</div>
                  知识抽取中，完成后右下角会通知您
                </div>
              )}
            </div>
            <Button size="small" type={pollRef.current ? 'default' : 'primary'}
              disabled={pollRef.current !== null}
              style={pollRef.current ? { color: '#c0c4cc', borderColor: '#e4e7ed' } : {}}
              onClick={() => {
                if (!book || pollRef.current) return
                // 立即锁定按钮，避免 await 期间重复点击
                pollRef.current = 'lock'
                const bid = book.id
                api.extractKnowledge(bid).then(r => {
                  message.success(r.message || '知识抽取已启动')
                  if (!pollRef.current) return // 已取消（组件卸载）
                  let attempts = 0
                  pollRef.current = setInterval(async () => {
                    attempts++
                    try {
                      const data = await api.getKnowledgeGraph(bid)
                      if (data.nodes && data.nodes.length) {
                        clearInterval(pollRef.current)
                        pollRef.current = null
                        setGraphExists(true)
                        notification.info({
                          message: '知识图谱',
                          description: '知识抽取已完成',
                          placement: 'bottomRight',
                          duration: 6,
                        })
                        if (activeTab === 'knowledge') loadGraph(bid)
                      }
                    } catch {}
                    if (attempts > 180) { clearInterval(pollRef.current); pollRef.current = null }
                  }, 10000)
                })
              }}>
              {pollRef.current ? '生成中...' : '生成图谱'}
            </Button>
          </div>
        )}
      </div>
      {/* 右侧竖排 tab 标签 */}
      <div style={{ width: 56, display: 'flex', flexDirection: 'column', background: '#fff', borderLeft: '1px solid #e4e7ed', flexShrink: 0, alignItems: 'center' }}>
        {TABS.map(tab => (
          <div key={tab.key}
            onClick={() => onTabChange(tab.key)}
            style={{ padding: '10px 0', textAlign: 'center', cursor: 'pointer', borderBottom: '1px solid #e4e7ed', color: tab.key === activeTab ? '#409eff' : '#909399', width: '100%', background: tab.key === activeTab ? '#f0f7ff' : 'transparent' }}>
            <div style={{ fontSize: 16 }}>{tab.icon}</div>
            <div style={{ fontSize: 10, marginTop: 2 }}>{tab.label}</div>
          </div>
        ))}
      </div>
    </div>
  )
}
